# -*- coding: utf-8 -*-
"""agenteval_llm_judge_homework (SDEs + DEs).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mqodfxUErni_ZTqgwdniQsekA3e73_m6

# 🧪 LLM Judge Homework: Step-by-Step Evaluation
In this assignment, you'll incrementally build an LLM-based judge to compare two summaries.

You'll go through the following steps:
1. Base judgment: which is better overall?
2. Add rubric: accuracy, coverage, clarity
3. Add explanations per rubric
4. Add chain-of-thought reasoning
"""

!pip install openai

import openai
from getpass import getpass
#from google.colab import userdata
#openai.api_key = userdata.get('OPENAI_API_KEY')
#print(openai.api_key)
openai.api_key = getpass('Enter your OpenAI API key: ')
client = openai.OpenAI(api_key=openai.api_key)

"""## 🧾 Example Set"""

examples = [
    {
        "id": "ex1",
        "context": "The UN released a report warning of global temperature rise and called for urgent international action.",
        "summary_a": "The UN warned that climate change is worsening and action is needed.",
        "summary_b": "The UN praised global progress in reducing emissions."
    },
    {
        "id": "ex2",
        "context": "NASA launched Artemis I, an uncrewed spacecraft that will orbit the Moon and return to Earth, preparing for human missions.",
        "summary_a": "NASA launched Artemis I to prepare for future Moon missions.",
        "summary_b": "NASA's Artemis I failed to launch due to engine problems."
    },
    {
        "id": "ex3",
        "context": "A study found intermittent fasting improves blood sugar and cholesterol levels.",
        "summary_a": "Intermittent fasting improves health markers like blood sugar and cholesterol.",
        "summary_b": "Fasting was linked to poor nutrition and increased blood pressure."
    }
]

"""## 🔹 Step 1: Base Judgment – A or B?
No rubric, just pick the better one and explain.
"""

def judge_base(context, summary_a, summary_b,client):
    prompt = f'''
You're evaluating two summaries of an article.

Article:
\"\"\"{context}\"\"\"

Summary A:
\"\"\"{summary_a}\"\"\"

Summary B:
\"\"\"{summary_b}\"\"\"

Which one is better and why? Reply in JSON:
{{
  "final_answer": "A" or "B",
  "explanation": "..."
}}
'''
    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[{"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content

import json
def run_judge_base(client):
    print("Running Step 1: Base Judgment")
    for ex in examples:
        result = judge_base(ex['context'], ex['summary_a'], ex['summary_b'],client)
        print(result)

run_judge_base(client)

"""## 🔹 Step 2: Add Rubric Dimensions – Accuracy, Coverage, Clarity"""

def judge_with_rubric(context, summary_a, summary_b, client):
#     prompt = f'''
# <<YOUR PROMPT HERE>>
# '''
    prompt = f'''
You are an expert evaluator comparing two summaries (A and B) for the same context.

Evaluate them using this rubric:
1. **Factual Accuracy** – Does the summary correctly reflect the facts in the context?
2. **Coverage** – Does it capture the main ideas?
3. **Clarity** – Is it easy to understand and well-written?

Context:
{context}

Summary A:
{summary_a}

Summary B:
{summary_b}

Please respond in **valid JSON** with this structure:
{{
  "factual_accuracy": "Explanation and which summary is more accurate",
  "coverage": "Explanation and which summary covers more key ideas",
  "clarity": "Explanation and which summary is clearer",
  "final_decision": "A or B",
  "justification": "1-2 sentence summary of why that summary was better overall"
}}
'''
#    prompt = f'''
#    Evaluate two summaries using this rubric (0–10 per dimension):
#- Accuracy
#- Coverage
#- Clarity
#
#Article:
#\"\"\"{context}\"\"\"
#
#Summary A:
#\"\"\"{summary_a}\"\"\"
#
#Summary B:
#\"\"\"{summary_b}\"\"\"
#
#Respond in JSON:
#{{
#  "summary_a": {{"accuracy": int, "coverage": int, "clarity": int}},
#  "summary_b": {{"accuracy": int, "coverage": int, "clarity": int}},
#  "final_answer": "A" or "B"
#}}
#
#
#    '''
    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[{"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content

import json
def run_judge_base(client):
    print("Running Step 1: Base Judgment")
    for ex in examples:
        result = judge_with_rubric(ex['context'], ex['summary_a'], ex['summary_b'],client)
        print(result)

run_judge_base(client)

"""## 🔹 Step 3: Add Explanations per Rubric Dimension and OneShot"""

def judge_with_rubric_expl(context, summary_a, summary_b, client):
#     one_shot = '''
# <<YOUR ONE_SHOT HERE>>
# '''
#    one_shot = '''
### ONE-SHOT EXAMPLE (Follow this style)
#
#Article:
#\"\"\"Example Article\"\"\"
#
#Summary A:
#\"\"\"Example A\"\"\"
#
#Summary B:
#\"\"\"Example B\"\"\"
#
#JSON Output Example:
#{{
#  "scores": {{
#    "A": {{
#      "accuracy": 4,
#      "accuracy_explanation": "A covers most facts correctly.",
#      "coverage": 3,
#      "coverage_explanation": "A misses some important points.",
#      "clarity": 5,
#      "clarity_explanation": "A is very easy to read."
#    }},
#    "B": {{
#      "accuracy": 5,
#      "accuracy_explanation": "B is fully aligned with the article.",
#      "coverage": 4,
#      "coverage_explanation": "B covers slightly more points.",
#      "clarity": 4,
#      "clarity_explanation": "Clear but slightly less structured."
#    }}
#  }},
#  "final_answer": "B",
#  "explanation": "B is more accurate and covers more important points overall."
#}}
#'''

#     prompt = f'''
# {one_shot}

# <<YOUR PROMPT HERE>>

# }}
# '''
#    prompt = f'''
#  {one_shot}
#
#
#  Evaluate two summaries using this rubric:
#  1. Accuracy – How faithful the summary is to the article.
#  2. Coverage – How many important points it includes.
#  3. Clarity – How clear & readable it is.
#
#  Provide:
#  - A score (1–5) for each dimension.
#  - An explanation FOR EACH SCORE.
#  - A final winner ("A" or "B").
#
#  Article:
#  \"\"\"{context}\"\"\"
#
#  Summary A:
#  \"\"\"{summary_a}\"\"\"
#
#  Summary B:
#  \"\"\"{summary_b}\"\"\"
#
#  Respond in Valid JSON
#  '''



    # Solution
    one_shot = '''
Example:

Article:
"""The Mars rover Perseverance successfully collected its first rock samples, which will help scientists study signs of ancient life on Mars."""

Summary A:
"""Perseverance gathered its first rock samples, advancing the mission to study past Martian life."""

Summary B:
"""NASA’s rover was unable to collect samples due to a drilling malfunction."""

Evaluation:
{
  "summary_a": {
    "accuracy": 9,
    "accuracy_explanation": "Accurately reflects that the rover collected samples and the purpose of the mission.",
    "coverage": 9,
    "coverage_explanation": "Covers both the sampling and the scientific goal.",
    "clarity": 9,
    "clarity_explanation": "Clear and concise summary with no ambiguity."
  },
  "summary_b": {
    "accuracy": 2,
    "accuracy_explanation": "Factually incorrect — the rover did collect samples successfully.",
    "coverage": 3,
    "coverage_explanation": "Misses all key points from the article and introduces incorrect information.",
    "clarity": 7,
    "clarity_explanation": "Somewhat clear, but misleading due to false claims."
  },
  "final_answer": "A"
}

---
'''

    prompt = f'''
    {one_shot}

    Now evaluate the following:

    Article:
    \"\"\"{context}\"\"\"

    Summary A:
    \"\"\"{summary_a}\"\"\"

    Summary B:
    \"\"\"{summary_b}\"\"\"

    }}
    '''

    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[{"role": "system", "content": "You are a strict JSON evaluator for summarization quality using rubric dimensions."},
                  {"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content.strip()

def run_judge_rubric_expl(client):
    print("Running Step 3: Rubric + Explanation")
    for ex in examples:
        result = judge_with_rubric_expl(ex['context'], ex['summary_a'], ex['summary_b'],client)
        print(result)

run_judge_rubric_expl(client)

"""## 🔹 Step 4: Add Chain-of-Thought Reasoning"""

def judge_chain_of_thought(context, summary_a, summary_b, client):
#    prompt = f"""
#You are evaluating two summaries of the following article:
#
#Article:
#\"\"\"{context}\"\"\"
#
#Summary A:
#\"\"\"{summary_a}\"\"\"
#
#Summary B:
#\"\"\"{summary_b}\"\"\"
#
#Think step-by-step:
#1. Compare factual accuracy between A and B.
#2. Compare their coverage of main ideas.
#3. Compare clarity and readability.
#4. Based on reasoning, assign scores and explain.
#
#Return a JSON with this format:
#{{
#  "accuracy": "A" or "B" or "tie",
#  "coverage": "A" or "B" or "tie",
#  "clarity": "A" or "B" or "tie",
#  "accuracy_reasoning": "...",
#  "coverage_reasoning": "...",
#  "clarity_reasoning": "...",
#  "final_answer": "A" or "B",
#  "overall_reasoning": "..."
#}}
#"""

    prompt = f"""

Now evaluate:

Article:
\"\"\"{context}\"\"\"

Summary A:
\"\"\"{summary_a}\"\"\"

Summary B:
\"\"\"{summary_b}\"\"\"

Reason step-by-step through **each dimension** before assigning scores.

Respond only in JSON:
{{
  "reasoning": "...",
  "summary_a": {{"accuracy": int, "coverage": int, "clarity": int}},
  "summary_b": {{"accuracy": int, "coverage": int, "clarity": int}},
  "final_answer": "A" or "B"
}}
"""

    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": "You are a rubric-based evaluator that reasons step-by-step before scoring."},
            {"role": "user", "content": prompt}
        ]
    )
    return response.choices[0].message.content.strip()

def run_judge_chain_of_thought(client):
    print("Running Step 4: Chain-of-Thought Judgment")
    for ex in examples:
        result = judge_chain_of_thought(ex['context'], ex['summary_a'], ex['summary_b'],client)
        print(result)

run_judge_chain_of_thought(client)

