# -*- coding: utf-8 -*-
"""Assignment_Movie_Review_Sentiment_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_6uw6w2GmbtA8v2-S_sdZQz1iYZmEh5c

IMDB movie review dataset sentiment analysis


The [IMDB movie review dataset](https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews) has 50k movie reviews. Each review has a binary sentiment classification label "positive" or "negative". We will use LLMs to perform movie review sentiment classification.

By the end of the assignment, you will gain hands on experience with
* Zero / Few shot the LLM to perform movie review sentiment analysis
* Evaluate accuracy of the sentiment predictions
"""

# This cell mounts the assignment data directory to allow file read.
# Please first add the class content directory "Module 6 : Deep Dive Into LLMs - V"
# as a short cut under your Google Drive, before you execute the cell. During
# execution, you will be prompted to give permissions to the drive mounting
# operation.

import os

from google.colab import drive
drive.mount('/content/drive')
assets_dir = '/content/drive/MyDrive/Module 6 : Deep Dive into LLMs - V2/Assignment and MCQs/datasets/'

"""### Problem: Classify the sentiment of IMDB movie review as either `positive` or `negative`"""

# Parse the csv data file "IMDB_Dataset.csv" into a data frame.
# The data frame has 2 columns, "review" and "sentiment":
# * review: The text of an IMDB movie review.
# * sentiment: Groundtruth sentiment label of the review. Has two possible
#     values: "positive" and "negative".
import pandas as pd

df_reviews = pd.read_csv(os.path.join(assets_dir, 'IMDB_Dataset.csv'))

# view the first 3 rows of the data frame.
df_reviews.head(3)

# view full text of the first review in the data frame.
df_reviews.iloc[0].review

import torch
import transformers

transformers.utils.logging.set_verbosity_error()
device = 'cuda' if torch.cuda.is_available() else 'cpu'

#@title Download phi-3 model and its tokenizer from hugging face

from transformers import AutoModelForCausalLM, AutoTokenizer

phi3_model = AutoModelForCausalLM.from_pretrained("microsoft/Phi-3-mini-4k-instruct",
                                             torch_dtype="auto",
                                             trust_remote_code=True
                                             )
phi3_tokenizer = AutoTokenizer.from_pretrained("microsoft/Phi-3-mini-4k-instruct")

"""### Zero Shot and Few Shot Sentiment Analysis

* IMDB movie review sentiment analysis
We want to predict the sentiment of IMDB movie reviews as either "positive" or "negative". We can solve the problem with an LLM, by instructing the model using zero shot or few shot prompts, tailored for movie review sentiment analysis. Our goal is to make the model generate response strings equal to either "positive" or "negative".

* In zero-shot prompting, we instruct the model the generate text to complete the desired task. For example, for a translation task, we can write the following prompt:
```
Translate the sentence below to French.
Sentence: Today is sunny.
Translation:
```
Generally, we want the prompt to end in a instructional tone/wording that the model can understand as "it's now my turn to complete the task". In the translation prompt above, we do this by ending the prompt with "Translation:".

* In few-shot prompting, we also instruct the model the generate text to complete the desired task. But now we also additionally include a few examples. These examples should ideally be representative of the real data, and have sufficient coverage of desired model behavior. For example, suppose we want the model to judge whether an input is humurous, it helps to show the model a "yes" example and a "no" example. Figuring out the number of examples we include and the content of the examples are part of prompt engineering.
```
Judge whether the sentence is funny. Answer "yes" or "no". Here's some examples.
Sentence: Why was six afraid of seven? Because seven eight nine.
Answer:yes
Sentence: I had an omelette this morning.
Answer:no
Now it's your turn.
Sentence: Did you hear about the shepherd who drove his sheep through town? He was given a ticket for making a ewe turn.
Answer:
```

* Zero shot and few shot prompts for movie review sentiment analysis should include
  * Instructions describing the task to the model.
  * A few examples when using few shot.
  * The specific movie review we want to predict sentiment for.

### (YOUR CODE HERE) Complete the functions building zero shot and few shot prompts.
Python's string formatting (see https://realpython.com/python-string-formatting/ for details) is very helpful to combine instructions, examples along with specific reviews.
```
review = "5 stars"
formatted_prompt = "Rate this movie as {review}".format(review=review)
print(formatted_prompt)

>>> "Rate this movie as 5 stars"
```
"""

def zero_shot_prompt(review: str):
  """Return zero shot prompt."""

def few_shot_prompt(review: str):
  """Return few shot prompt"""

"""### (YOUR CODE HERE) Complete `generation_args`

We have preprared a sentiment prediction function using Hugging face `transformers` package's `pipeline` object:. https://huggingface.co/microsoft/Phi-3-mini-4k-instruct shows example usage.

The `pipeline` object is initialized with the LLM model and its tokenizer. It takes a text prompt as input, and returns the model's text response. Under the hood, the `pipeline` tokenizes text input, calls the LLM, decode token ids from the LLM, and finally decodes token ids back to text. For the caller, this provides an easy "text in text out" interface with the LLM.

The `predict_sentiment` function below expects pre-loaded LLM model and tokenizer, as well as a zero/few shot prompt we built for movie review sentiment analysis. It returns the model's sentiment prediction for the  prompt in text.

Within the function, `generation_args` controls LLM decoding behavior. Complete the configuration of `generation_args` by replacing `None` with appropriate values if needed. You can find documentation of various generation config parameters in https://huggingface.co/docs/transformers/v4.42.0/en/main_classes/text_generation#transformers.GenerationConfig.
"""

from transformers import pipeline

def predict_sentiment(model, tokenizer, prompt):
  pipe = pipeline(
      "text-generation",
      model=model,
      tokenizer=tokenizer,
      device=device,
  )

  generation_args = {
      "max_new_tokens": None,         # how many max tokens to decode from the LLM
      "return_full_text": False,      # only return response (and exclude input prompt)
      "temperature": None,            # what temperature to use for LLM decoding
      "do_sample": None,              # boolean variable. when False, perform greedy decode. otherwise decode temperature is specified by "temprature" config above.
  }

  messages = [{"role": "user", "content": prompt}]
  chat_prompt = phi3_tokenizer.apply_chat_template(messages, add_generation_prompt=True, tokenize=False)
  return pipe(chat_prompt, **generation_args)[0]['generated_text']

"""### (YOUR CODE HERE) Compare Zero Shot vs Few Shot Sentiment Analysis  Accuracy

The IMDB moview review dataset has 50k examples. This is too much compute for the assignment. We will look at the first `n` examples in the dataset. Feel free to adjust `n` according to your compute budget.

Compte the two function below to run zero shot and few shot sentiment analysis, and compute accuracy for both methods.
* Which method is more accurate?
* Does accuracy change with prompt modification?
"""

def zero_shot_sentiment_analysis(n=100):
  for _, row in df_reviews.iloc[0:n].iterrows():
    review = row.review
    sentiment = row.sentiment
    """
    Your code:
    * Use the LLM to predict the sentiment of `review` using zero shot prompt,
      and compare the ground truth `sentiment`.
    * Define and implement an accuracy metric for the LLM's sentiment
      prediction.
    """

def few_shot_sentiment_analysis(n=100):
  """
  Your code:
  * Use the LLM to predict the sentiment of `review` using few shot prompt,
    and compare the ground truth `sentiment`.
  * Define and implement an accuracy metric for the LLM's sentiment
    prediction.
  """