# -*- coding: utf-8 -*-
"""Building_RAG_Application.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CC-urhCHJq-Yo7I6dRiwpNpKa-GDYBZd

# **Building a RAG Application: A Comprehensive Demo**

In today's digital healthcare landscape, patients and medical professionals frequently seek accurate, up-to-date answers to a wide range of medical questions. However:

- Search engines return too much noise or unverified sources.

- Chatbots often hallucinate or give generic advice without referencing valid information.

- Medical professionals/Patients have limited time to find contextually relevant evidence or literature.

There is a growing need for an AI system that can:

- Provide precise, evidence-backed answers,

- Maintain context awareness during multi-turn conversations,

- And optionally enhance its knowledge using trusted real-time web sources.

### **Objective:**
In this notebook, you will explore the Retrieval-Augmented Generation (RAG) framework and its application to Large Language Models (LLMs), specifically in the context of a Medical Assistant Chatbot.

You will:

- **Set up the necessary libraries** and tools for implementing RAG with LLMs.

By the end of this demo, you will understand the RAG framework and its practical applications in enhancing LLMs.

\

---

\

### **What is RAG?**

**Retrieval-Augmented Generation (RAG)** is an advanced method to enhance **LLMs** with external knowledge. Instead of relying solely on the model's pre-trained knowledge, RAG allows the LLM to retrieve relevant information from external databases (like vector stores) during inference, making it suitable for dynamic and domain-specific applications.

RAG addresses many challenges faced by LLMs:
- **Domain Knowledge Gaps**: LLMs can be limited in specific knowledge areas, especially in evolving fields.
- **Factuality Issues & Hallucinations**: RAG helps reduce incorrect or fabricated answers by retrieving context from trusted data sources.
- **Real-Time Updates**: RAG enables the integration of continuously updated external knowledge without retraining the model.

\

---

\


### **Why Use RAG?**

RAG enhances the capabilities of LLMs by:
- **Improving Response Quality**: Provides context from up-to-date knowledge, making the response more accurate.
- **Handling Knowledge Gaps**: Allows LLMs to access external databases, which are often required for specialized tasks.
- **Reducing Hallucinations**: RAG reduces the risk of LLMs making up answers or providing misleading responses.
- **Faster Deployment**: RAG avoids the need for retraining the model for every new dataset or domain.

> For more detailed information, you can refer to this [RAG Paper](https://arxiv.org/abs/2312.10997) or the [Retrieval-Augmented Generation Blog](https://www.promptingguide.ai/research/rag.en#introduction-to-rag).

### **Step 1. Setup and Install Dependencies**

> Run the following cell to install dependencies required:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# # 🧹 Clean up anything that could interfere
# !pip uninstall -y langchain langchain-core langchain-community langchain-openai langchain-huggingface openai gradio transformers faiss-cpu sentence-transformers > /dev/null
# 
# # Upgrade tooling
# !pip install -q --upgrade pip setuptools wheel
# 
# # Install compatible, verified versions step by step
# !pip install -q langchain-core==0.3.15
# !pip install -q langchain==0.3.15
# !pip install -q langchain-community==0.3.15
# !pip install -q langchain-openai==0.2.11
# !pip install -q langchain-huggingface==0.3.1
# !pip install -q openai==1.58.1
# !pip install -q transformers==4.46.2
# !pip install -q faiss-cpu==1.8.0.post1
# !pip install -q gradio==4.44.0 jedi==0.19.1
# 
# # ✅ Verify that everything now imports correctly
# from openai import OpenAI
# from langchain_openai import ChatOpenAI, OpenAIEmbeddings
# from langchain.text_splitter import RecursiveCharacterTextSplitter
# from langchain_community.vectorstores import FAISS
# from langchain_huggingface import HuggingFaceEmbeddings
# 
# print("✅ Everything installed and imported successfully!")
#

# 💻🔄 Restart runtime to reload environment
import os
os._exit(0)

# Import the warnings module and suppress any warnings that might appear during execution
import warnings
warnings.filterwarnings("ignore")  # Ignore warnings to keep the output clean and focused

"""- The `warnings` module is used to manage and control the warning messages in Python.
- `filterwarnings("ignore")` tells Python to ignore all warning messages that may be raised during execution. This is often done to keep the notebook or script output cleaner, especially when warnings are known and not critical to the code's functionality.

### **Step 2. Imports and Configuration**
"""

import os
# import openai
from openai import OpenAI
from langchain.text_splitter import CharacterTextSplitter
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.vectorstores import FAISS
import getpass

"""### **Step 3. Add OpenAI API Key**

[Models available](https://platform.openai.com/docs/models)

#### **📌 Best Practices for API Key Safety**


1. Always use a unique API key for each team member on your account
2. Never deploy your key in client-side environments like browsers or mobile apps
3. Never commit your key to your repository
4. Use Environment Variables in place of your API key
5. Use a Key Management Service
6. Monitor your account usage and rotate your keys when needed
"""

from google.colab import userdata
OPENAI_API_KEY = userdata.get('OPENAI_API_KEY')
print(f"OPENAI_API_KEY: {OPENAI_API_KEY[:10]} ...")
os.environ['OPENAI_API_KEY'] = OPENAI_API_KEY
# os.environ['OPENAI_API_KEY'] = getpass.getpass()

client = OpenAI()

"""#### **🛡️ Further Details**

1. Use .env Files for Local Development
  - Store the API key in a .env file and load it using dotenv.

    ```
    from dotenv import load_dotenv
    load_dotenv()
    API_KEY = os.getenv("OPENAI_API_KEY")
    ```
2. Use Secret Managers for Production
  - AWS: AWS Secrets Manager
  - Azure: Azure Key Vault
  - GCP: Google Secret Manager

3. Use Token-Based Authentication if Available
  - Some cloud services provide temporary tokens instead of static API keys.

### **Step 4. Text Cleaning and Preprocessing**

> We now clean and preprocess the data. The text needs to be formatted before it can be processed into vector embeddings.

#### **1. Upload the Dataset**
> (dataset.txt)
"""

# from google.colab import files

# # Upload the CSV files
# uploaded = files.upload()

# # Verify files uploaded successfully
# print(uploaded)

!gdown 1727UCcg_Nxn9Nbj_LiX8pvGEpo591oxc

# Read and clean the dataset
with open('ai-medical-chatbot.txt', 'r') as f:
    data = f.read()

data = data.replace('\n\n','\n') # Clean unnecessary line breaks
data = data.split('---') # Split the data into separate sections based on a delimiter

len(data)

print(data[3])

print(data[4])

# Preprocess the text (adjust formatting for clean text)
for i in range(0, len(data)):
    if i==4:
      data[i] = data[i].replace('\n**', '\n###').replace('**','')
    else:
      data[i] = data[i].replace('**','')

print(data[3])

print(data[4])

# Organize the data into question-answer pairs
ques_ans = dict()
for i in range(0, len(data)):
    topics = data[i].split('\n###')
    for topic in topics[1:]:
      question_answer_pair = topic.split('\n')
      ques_ans[question_answer_pair[0]] = " ".join(question_answer_pair[1:])

len(ques_ans)

ques_ans.keys()

print(ques_ans[" What are Medical Conditions?"])

all_content = str()
for key, value in ques_ans.items():
    # print(key)
    all_content += key + " " + value + "\n"
# print(all_content)
# Print cleaned content for verification

print(all_content)

"""#### **2. Text Chunking**

> To prepare the text for semantic search, we break the content into smaller chunks. This will make it easier to process and index efficiently.

"""

# Split the large content into smaller chunks for indexing
text_splitter = CharacterTextSplitter(separator='\n', chunk_size=300, chunk_overlap=128, length_function=len)

chunks = text_splitter.split_text(all_content)

# Display the first chunk for verification
print(chunks)

len(chunks)

"""#### **4. Store Embeddings in FAISS**

> We use FAISS to store and index the vectors. FAISS is optimized for similarity search, allowing us to retrieve the most relevant vectors during the search phase.
"""

embeddings = OpenAIEmbeddings()

vectorStore = FAISS.from_texts(chunks, embeddings)
vectorStore.save_local("faiss_doc_idx")

"""#### **5. Perform Semantic Search**

> Now that we have indexed the embeddings, we can perform a semantic search. This search will find the most relevant documents based on a query, considering the meaning rather than exact matches.
"""

docs = vectorStore.similarity_search("What are the main differences between acute and chronic medical conditions?")

# """
# - What does abutment of the nerve root mean in MRI reports?
# - What is the treatment for L5-S1 disc bulge?
# - What does mild concentric left ventricular hypertrophy mean?
# - How can I lose weight with hypothyroidism?
# """

len(docs)

for doc in docs:
    print(doc.page_content)

docs = vectorStore.similarity_search("I have pain in arm, should I consult multiple doctors?")
for doc in docs:
    print(doc.page_content)

"""#### 6. **Setup OpenAI Model**

"""

from langchain_community.llms import HuggingFaceHub

import os
from langchain.prompts import PromptTemplate
from langchain.chains import RetrievalQA
from langchain_community.llms import OpenAI

question = "What are the main differences between acute and chronic medical conditions?"


llm = OpenAI()
template = """You are a medical assistant chatbot helping answer patient questions based only on the provided context.
Do not guess or provide inaccurate information. If the answer is not found in the context, say you don’t know.
You will answer the question based on the context - {context}.
Question: {question}
Answer:"""
QA_CHAIN_PROMPT = PromptTemplate.from_template(template)

# Create Retrieval QA Chain
qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=vectorStore.as_retriever(search_type="similarity", k=4),
    chain_type_kwargs={"prompt": QA_CHAIN_PROMPT}
)

# Run the chain with the user query
result = qa_chain({"query": question})
answer = result['result']

print("answer is\n", answer)

print("answer is\n", answer)

result.keys()

"""### **Step 5. Gradio Chatbot**"""

from langchain.prompts import PromptTemplate
from langchain.chains import RetrievalQA

from langchain.prompts import PromptTemplate
from langchain.chains import RetrievalQA
from langchain.chat_models import ChatOpenAI
from langchain.schema import AIMessage, HumanMessage
import gradio as gr
import traceback

# Toggle this flag to True to enable debug logs
DEBUG = True

def predict(message, history):
    try:
        if DEBUG: print(f"\n📥 Received message: {message}")
        history_langchain_format = []

        # Convert chat history into LangChain format
        for human, ai in history:
            history_langchain_format.append(HumanMessage(content=human))
            history_langchain_format.append(AIMessage(content=ai))

        # Define Prompt
        template = """You are a medical assistant chatbot helping answer patient questions based only on the provided context.
        Do not guess or provide inaccurate information. If the answer is not found in the context, say you don’t know.
        You will answer the question based on the context - {context}.
        Question: {question}
        Answer:"""
        QA_CHAIN_PROMPT = PromptTemplate.from_template(template)

        # Create Retrieval QA Chain
        qa_chain = RetrievalQA.from_chain_type(
            llm=llm,
            retriever=vectorStore.as_retriever(search_type="similarity", k=4),
            chain_type_kwargs={"prompt": QA_CHAIN_PROMPT}
        )

        # Run the chain with the user query
        result = qa_chain({"query": message})
        answer = result['result']

        if DEBUG: print(f"✅ Retrieved Answer:\n{answer}")

        # Update history
        history_langchain_format.append(HumanMessage(content=message))
        history_langchain_format.append(AIMessage(content=answer))

        return answer

    except Exception as e:
        error_trace = traceback.format_exc()
        if DEBUG: print(f"❌ Exception occurred:\n{error_trace}")
        return "⚠️ Sorry, an internal error occurred. Please try again later."

# Gradio Chatbot UI
gr.ChatInterface(
    fn=predict,
    chatbot=gr.Chatbot(height=300),
    textbox=gr.Textbox(placeholder="Ask me a question related to Healthcare and Medical Services", container=False, scale=7),
    title="DocumentQABot",
    theme="soft",
    examples=[
        "What are the main differences between acute and chronic medical conditions?",
        "What are the main differences between acute and chronic medical conditions?",
        "What does mild concentric LV hypertrophy mean?"
    ],
    retry_btn=None,
    undo_btn="Delete Previous",
    clear_btn="Clear",
).launch(share=True)

"""---
#  -----------------------------------------------------  **THANK YOU** ------------------------------------------------------------


---
"""