# -*- coding: utf-8 -*-
"""Conventional_Bots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TXZxGwdJT5XoLbVeLqHs1BGbeiSAuiVQ

# **Conventional_Bots**

## 🤖 **Rule based Conventional System**

First we'll build a **simple rule-based System** — a chatbot that responds to user inputs based on predefined rules.

This is your first step toward understanding how AI agents work. Unlike machine learning models, rule-based agents follow **if-then** logic to make decisions.

By the end of this part, you will:
- Understand what a rule-based system is
- Build a chatbot that can respond to basic inputs
- See where rule-based agents fall short

#### 🧩 **What is a Rule-Based System?**

A **rule-based Systemt** operates on hard-coded rules. These rules define what the system should do when it encounters specific input.

For example:

- If someone says "hello", respond with "Hi there!"
- If someone asks for your name, respond with "I'm a chatbot!"

This type of system does **not learn** or adapt — it's predictable and easy to implement, but not flexible.

You'll now create your first rule-based chatbot below.
"""

# 🔧 Rule-based chatbot function

def rule_based_chatbot(user_input):
    user_input = user_input.lower()

    if "hello" in user_input or "hi" in user_input:
        return "Hello! How can I assist you today?"
    elif "your name" in user_input:
        return "I'm a simple rule-based chatbot."
    elif "weather" in user_input:
        return "I can't provide live weather updates, but it's a nice day to code!"
    elif "bye" in user_input or "goodbye" in user_input:
        return "Goodbye! Have a great day."
    else:
        return "I'm not sure how to respond to that. Can you try rephrasing?"

"""#####💡 **Try it!**

Type something like:
- "Hi"
- "What's your name?"
- "Tell me the weather"
- "Bye"

To exit the chatbot, type `exit`.

Think about:
- What happens when you ask something unexpected?
- Can you add more rules to improve it?

"""

# 🔁 Run a loop to chat with the bot
while True:
    user_input = input("You: ")
    if user_input.lower() == "exit":
        print("Chatbot: Session ended.")
        break
    response = rule_based_chatbot(user_input)
    print("Chatbot:", response)

"""#### 🚧 **Limitations of Rule-Based Systems**

While rule-based systems are easy to build and understand, they come with significant limitations:

- ❌ Not scalable: You need to write a rule for every possible input
- ❌ No learning: Can't improve or adapt on its own
- ❌ Poor at handling ambiguous or fuzzy input (e.g., typos, synonyms)

This is where **LLM-based agents** like ChatGPT and LangChain agents shine.

In the next notebook, you'll learn to build agents that use **language models** to reason and act intelligently.

"""