# -*- coding: utf-8 -*-
"""FewShot_vs_FineTuned_Summarization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13nEHMmg3HrDFZ9GQRKYBDYwwbuF88Arn

#  Few-Shot vs. Fine-Tuned Summarization Comparison

This notebook demonstrates how to compare the performance of few-shot prompting with instruction-tuned models vs. fine-tuned summarization models (like BART).
"""

!pip install -q transformers datasets ipywidgets

#  Sample: Simulated movie reviews
movie_reviews = """
The movie delivered an emotionally powerful story that felt authentic and heartfelt.
Some scenes relied too heavily on CGI, which distracted from the otherwise grounded narrative.
The lead actress gave a phenomenal performance that carried many of the film’s key moments.
Pacing was uneven, with a slow first act followed by a rushed finale.
Despite its flaws, the film left a lasting impression and sparked meaningful discussion afterward.
"""

"""##  1. Few-Shot Prompted Summarization (FLAN-T5)"""

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import time

few_shot_prompt = f"""
You are an assistant that summarizes groups of movie reviews into an overall sentiment and the main points in exactly 3 sentences.

### Example
Input:
The film was a visual masterpiece with stunning cinematography.
However, the plot felt slow and predictable.
Great performances by the lead actors.
The score complemented the tone perfectly.
It dragged a bit in the middle but the ending was satisfying.

Output:
The overall sentiment is positive, highlighting the film’s strong visuals, performances, and score. Reviewers noted that the pacing lagged at times and the plot was somewhat predictable. Despite this, the conclusion was regarded as satisfying.

### Task
Given the following movie reviews, summarize the overall sentiment and main points in exactly 3 sentences.

Input:
{movie_reviews}

Output:
"""

model_name = "google/flan-t5-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

inputs = tokenizer(
    few_shot_prompt,
    return_tensors="pt",
    max_length=512,
    padding="max_length",
    truncation=True
)

start_time = time.time()
outputs = model.generate(
    **inputs,
    max_new_tokens=100,
    temperature=0.7,
    top_k=50,
    top_p=0.95
)
end_time = time.time()

few_shot_summary = tokenizer.decode(outputs[0], skip_special_tokens=True)
print("Few-shot Prompted Summary:\n")
print(few_shot_summary)
print(f"FLAN-T5 Inference Time: {end_time - start_time:.2f} seconds")

"""## 2. Fine-Tuned Summarization (BART)"""

from transformers import pipeline
import time

try:
    summarizer = pipeline("text-generation", model="facebook/bart-large-cnn")
    start_time = time.time()
    summary = summarizer(movie_reviews, max_length=100, min_length=30, do_sample=False)
    end_time = time.time()
    print(" Fine-tuned Summarizer Output:\n")
    print(summary[0]['summary_text'])
    print(f"BART Inference Time: {end_time - start_time:.2f} seconds")
except Exception as e:
    print(" Error during summarization:", e)

"""###  Comparison: Few-Shot vs. Fine-Tuned Summarizer

| Aspect | Few-Shot Prompting (FLAN-T5) | Fine-Tuned Summarizer (BART-CNN) |
|--------|-------------------------------|-----------------------------------|
| Setup  | Instruction-based prompt | Task-specific pre-trained weights |
| Flexibility | Works on any task with clever prompts | Performs best on summarization |
| Output Style | More generic or varied | Concise and on-topic |
| Customization | Requires good prompt design | Requires labeled data for training |
| Inference Time | Typically slower | Optimized for summarization |

"""

